### ISSUE TITLE
[Feature Request] Add straight up html and css version with a js to edit cells

### ISSUE THREAD

**Issue by wakatara** [neatnik/calendar#10]
Great work. 

While this is nice for printing, I think the ability to self-host this as static html with some js for cell editing for "year at a glance" online would be absolutely awesome as a static file serve. Right now, I use a ghetto approach with google calendar to do it which this would be much, much nicer for.

lemme know if you don't wanna. May take a shot myself.

**Comment by abetusk** [comment]
It sounds like you want more than one different feature.

Is this a fair breakdown?

* Static HTML, taking out the PHP/server side rendering dependency
* Add a facility to display additional text at each day cell location
* Add a user interface to add additional text at each day cell location

And when you say "static HTML", do you want no JavaScript dependency as an output/rendering option?

**Comment by wakatara** [comment]
@abetusk 

Thanks for considering the feature request! And yes, fair enough this is more a small feature set. The idea would be to find a way to make this statically serveable via S3 or github pages if possible. (love the idea, but having to run php makes it less secure and problematic as a server). 

1. static html with some added js
2. Display additional txt at each day location
3. js altering ability (so "statically" serveable) 

And js as a depedency is fine. I spoke poorly. I meant that the whol thing could be statically served really, or via existing infra a dev would normally have as tooling (ie GH pages etc.). 

Right now, I end up using a silly YAAG google shet to handle this so having a nice web editable version would be wicked (and heck even if not on the web, nice locally).
