### ISSUE TITLE
[Feature Request] Allow month selection

### ISSUE THREAD

**Issue by joanappardal** [neatnik/calendar#11]
Allow something like month=00 so we can print Academic Calendar (September to August).

**Comment by abetusk** [comment]
I hope I'm not being impolite to this repo by responding to this issue but I've forked the project and added extra parameters to allow for different month selection.

[Academic calendar example](https://abetusk.github.io/neatcal?start_month=8)

The repo can be found [here](https://github.com/abetusk/neatcal).
