### ISSUE TITLE
Align weekdays?

### ISSUE THREAD

**Issue by cadars** [neatnik/calendar#2]
More of a suggestion than an issue :)
Here's an example, a minimal one-page calendar I made in 2017, Sundays are in **bold**.

![image](https://user-images.githubusercontent.com/467112/108490804-713d2380-72a3-11eb-80c2-230e54aed8e2.png)

**Comment by newbold** [comment]
Just shy of 7 months later, I’ve finally had a chance to do this. Check it out in action here: https://neatnik.net/calendar/?layout=aligned-weekdays.

I’ve also updated the project README file with this info, but if you pass the `layout=aligned-weekdays` query string to the script, you’ll get the layout you mentioned. (Also new: you can pass a `year` parameter to render a calendar for that year.

**Comment by cadars** [comment]
Amazing, thanks for taking the time to make this happen!
