### ISSUE TITLE
Access to calendar version without darkened weekend cells?

### ISSUE THREAD

**Issue by rgl7194** [neatnik/calendar#8]
Sorry to be that guy - is there a way to get access to the version of the calendar without the darkened weekend cells?

**Comment by abetusk** [comment]
I hope I'm not being impolite to this repo by responding to this issue but I've forked the project and added extra parameters to modify the weekend highlighting color.

[Non-darkened weekend example](https://abetusk.github.io/neatcal?highlight_color=fff)

[Example with red highlighted weekends](https://abetusk.github.io/neatcal?highlight_color=fee)

The repo can be found [here](https://github.com/abetusk/neatcal).
